app/NotIMDB/config/routes.rb
Rails.application.routes.draw do

	resources :movies do
  		resources :comments, :only => [:create, :destroy]
	end
	get 'movies/:movie_id/comments/:id(.:format)' => 'comments#destroy'
  resources :movies do
    member do
     put :toggleon
    end
     collection do
       get :allrequest
     end
  end
  resources :movies

  get 'index'=>'movies#index'
  get 'request'=>'movies#new'
  root 'pages#home'
  get 'home' => 'pages#home'
  get 'single-movie'=>'pages#single-movie'
  get 'sign-up'=>'pages#sign-up'
  get 'show1'=>'movies#show1'
  get 'show/:id' => 'movies#show'
  post ':controller(/:action(/:id(.:format)))'
 get ':controller(/:action(/:id(.:format)))'
get 'requestedmovies' => 'movies#allrequest'

resources :users
get 'signup'  => 'users#new'
get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
get 'logout'  => 'sessions#destroy'

  
  
  resources :movies do
    resources :comments, :only => [:create]
  end

       resources :comments

end

app/NotIMDB/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  

  # GET /movies
  # GET /movies.json
  def index
  
  orderBy = ""

	if(params[:sort] == "titleAsc")
		orderBy = "title asc"
	elsif (params[:sort] == "titleDesc")
		orderBy = "title desc"
	elsif (params[:sort] == "rateAsc")
		orderBy = "rating asc"
	elsif (params[:sort] == "rateDesc")
		orderBy = "rating desc"
	end
	
   if params[:search] != ""
     
	 if (params[:filter_genre] == "All" && params[:filter_rating] == "")
	 		@movies = Movie.search(params[:search]).order(orderBy)
	elsif (params[:filter_genre] && params[:filter_rating] == "")
		@movies = Movie.searchFiltGenre(params[:search], params[:filter_genre]).order(orderBy)
	elsif (params[:filter_rating] && params[:filter_genre] == "All")
	  	@movies = Movie.searchFiltRate(params[:search], params[:filter_rating]).order(orderBy)
	elsif (params[:filter_genre] && params[:filter_rating])
		@movies = Movie.searchFiltBoth(params[:search], params[:filter_genre], params[:filter_rating]).order(orderBy)
	else
		@movies = Movie.search(params[:search]).order(orderBy)
	end
	
	else
	if (params[:filter_genre] == "All" && params[:filter_rating] == "")
			@movies = Movie.all.order(orderBy)	
	elsif (params[:filter_genre] && params[:filter_rating] == "")
		@movies = Movie.filterGenre(params[:filter_genre]).order(orderBy)		
	elsif (params[:filter_rating] && params[:filter_genre] == "All")
		@movies = Movie.filterRating(params[:filter_rating]).order(orderBy)	
	elsif (params[:filter_genre] && params[:filter_rating])
		@movies = Movie.filter(params[:filter_genre], params[:filter_rating]).order(orderBy)	
	else 
	@movies = Movie.all
	end
	
	end
end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])
    respond_to do |format|
      format.html #show.html.erb
	end
  end


  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
    if current_user.nil?
       flash[:danger] = "Please log in."
       redirect_to login_url        
      end
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    
      if @movie.save
        redirect_to index_url
        flash[:success] = "Movie was successfully created."         

      else
       render 'new'
       
      end
    end
 

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    Movie.find(params[:id]).destroy   
     flash[:success] = "Movie was successfully deleted."
     redirect_to index_url
  end

def toggleon
    @movie = Movie.find(params[:id])
    @movie.update_attributes(:viewable => true)
    if @movie.viewable?
       redirect_to index_url
        flash[:success] = "Movie was successfully added."    
    end
 end

def allrequest
  @movies = Movie.all
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :genre, :director, :actor1, :actor2, :actor3, :releaseyr, :rating, :description)
    end
    
     def viewable_movie
      redirect_to(index_url) unless movie.viewable?
    end
end

app/NotIMDB/app/helpers/movies_helper.rb
module MoviesHelper
end

app/NotIMDB/app/views/movies/_form.html.erb
<%= form_for (@movie), :html => {:class => "form-horizontal"} do |f| %>

  <div class="form-group">
    <%= f.label :title, for:"title", class:"control-label col-sm-2"%>
	<div class="col-sm-8">
		<%= f.text_field :title, id:"title", class: 'form-control' %>
	</div>
  </div>
  <div class="form-group">
    <%= f.label :genre, class:"control-label col-sm-2" %>
	<div class="col-sm-8">
    <%= f.text_field :genre, class:'form-control' %>
	</div>
  </div>
  <div class="form-group">
    <%= f.label :director, class:"control-label col-sm-2" %>
	<div class="col-sm-8">
    <%= f.text_field :director, class:'form-control' %>
	</div>
  </div>
  <div class="form-group">
    <%= f.label :actor1, class:"control-label col-sm-2" %>
	<div class="col-sm-8">
    <%= f.text_field :actor1, class:'form-control' %>
	</div>
  </div>
  <div class="form-group">
    <%= f.label :actor2, class:"control-label col-sm-2" %>
	<div class="col-sm-8">
    <%= f.text_field :actor2, class:'form-control'  %>
	</div>
  </div>
  <div class="form-group">
    <%= f.label :actor3, class:"control-label col-sm-2" %>
	<div class="col-sm-8">
    <%= f.text_field :actor3, class:'form-control'  %>
	</div>
  </div>
  <div class="form-group">
    <%= f.label :releaseyr, class:"control-label col-sm-2" %>
	<div class="col-sm-8">
    <%= f.number_field :releaseyr, class:'form-control'  %>
	</div>
  </div>
  <div class="form-group">
    <%= f.label :rating, class:"control-label col-sm-2" %>
	<div class="col-sm-8">
    <%= f.number_field :rating, class:'form-control'  %>
	</div>
  </div>
  <div class="form-group">
    <%= f.label :description, class:"control-label col-sm-2" %>
	<div class="col-sm-8">
    <%= f.text_area :description, class:'form-control'  %>
	</div>
  </div>
  <div class="actions">

    <%= f.submit "Submit", class: "btn btn-primary" %>

  </div>
<% end %>

app/NotIMDB/app/views/movies/allrequest.html.erb
<% if current_user.admin?%>
	<h1>Movies Waiting for Approval</h1>
	<% @movies.each do |movie| %>
	<%if !movie.viewable?%>
	
	<div class="panel panel-primary">
		<h3 class="panel-heading panel-title"><%= movie.title%></h3>
		<div class="panel-body">
			<p><%= movie.description %></p>
			<ul>
				<li>Directed by <%= movie.director %></li>
				<li>Starring  <%= movie.actor1 %>, <%= movie.actor2 %>, and  <%= movie.actor3 %></li>
				<li>Released <%= movie.releaseyr %></li>
				<li>Genre: <%= movie.genre %></li>
			</ul>
			<div class="form-group">
				<label class="control-label col-sm-2.5" for="poster_link">Link to Poster:</label>
				<input type="text" class="form-control" id="poster_link" placeholder="Enter Link">					
			</div>
			<div class="form-group">
				<label class="control-label col-sm-2.5" for="video_link">Link to Trailer:</label>
				<input type="text" class="form-control" id="video_link" placeholder="Enter Link">			
			</div>
			<div class="form-group">
				<label class="control-label col-sm-2.5" for="purchase">Link to Purchase:</label>
				<input type="text" class="form-control" id="purchase" placeholder="Enter Link">					
			</div>
		</div>
		<div class="panel-footer">
			<div class="row">
				<%= button_to "Accept", toggleon_movie_url(movie), class:"btn btn-success col-md-4", method: :put%>
				<%= button_to "Deny", movie, class:"btn btn-danger col-md-4", method: :delete, data: { confirm: "You sure?" } %>
			</div>
		</div>
	</div>
	
	<% end %>
	<% end %>
<%else%>
	<h1> You don't have access to this site! </h1>
<%end%>

app/NotIMDB/app/views/movies/edit.html.erb
<div id="container">
	<h1>Editing Movie</h1>
	<%= render 'form' %>
	<%= link_to 'Show', @movie %> |
	<%= link_to 'Back', movies_path %>
</div>

app/NotIMDB/app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<body>
  <div class="container">
      
	  <%= form_tag(movies_path, :method => "get") do %>
	<div id="container">
		<h1>All Movies</h1>
		<div class="navbar-form" style="text-align:center">
				<%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control", :search => params[:search] %>
				<%= submit_tag "Search", class: 'btn btn-default' %>
				<%= link_to "Clear", :type => "reset" %>
		</div>
		
		<div class="row">
			<div class="col-sm-6">
				<div>
					<div>
						<div class="well row">
						<div class="dropdown col-sm-6">
						 Genre: <br> 
						 <%= select_tag(:filter_genre, options_for_select([['All', 'All'],['Action', 'Action'], ['Adventure', 'Adventure'],['Animation', 'Animation'],
						 ['Comedy', 'Comedy'],['Drama', 'Drama'],['Romance', 'Romance'],['Sci-Fi', 'Sci-Fi']], 
						 :selected => params[:filter_genre]), :onchange => "this.form.submit();")%>
						</div>
						<div class="dropdown col-sm-6">
						 Rating: <br>
						  <%= select_tag(:filter_rating, options_for_select([['', ],['1', 1], ['2', 2],['3', 3],['4', 4],['5', 5]], :selected => params[:filter_rating]), 
						  :onchange => "this.form.submit();") %>
						  <br><br>
						</div>
						</div>	  
					</div>
				</div>
			</div>
	
			<div class="col-sm-6">
				<div>
					<div>
						<div class="well row">
						<div class="dropdown col-sm-6">
							Sort By: <br>
						<%= select_tag(:sort, options_for_select([['Featured', ''],['Title A-Z', 'titleAsc'], ['Title Z-A', 'titleDesc'],['Rating High-Low', 'rateDesc'], 
						['Rating Low-High', 'rateAsc']], :selected => params[:sort]), :onchange => "this.form.submit();")%>
						<br><br>
						</div>					
						</div>
					</div>
				</div>
			</div>
		</div>
		<% end %>
		
  <div class= "row">
    <% @movies.each do |movie| %>
    <%if movie.viewable?%>
		<%= link_to movie_path(movie.id), class:"movieCard col-md-4" do %>
			<% movie.title %>
				<h3><%= movie.title %></h3>
				 <span style="float: left;"><b>Genre:</b> <%= movie.genre %></span>
				 <span style="float: right;"><b>Rating:</b> <%= movie.rating %></span>
		  <% end %>
		  <%end%>
    <% end %>
	</div>


</body>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/NotIMDB/app/views/movies/new.html.erb
<div id="container">
	
	<h1>New Movie</h1>
	<%= render 'form' %>
	<%= link_to 'Back', home_path %>
</div>

app/NotIMDB/app/views/movies/show.html.erb
<div id="container">
<p id="notice"><%= notice %></p>

<%if @movie.viewable?%>
		<h1><%= @movie.title %></h1>

		<div style="text-align:center;margin-bottom:20px">
		<% @movie.rating.times do%>
			<%= image_tag "star.png", class:"star" %>
		<%end%>
		</div>

		<div class="row">
			<div class="col-md-4">
				<%= image_tag @movie.picture_link %>
			</div>
			<div class="col-md-8">
			<p><%= @movie.description %></p>
			<ul>
				<li>Directed by <%= @movie.director %></li>
				<li>Starring  <%= @movie.actor1 %>, <%= @movie.actor2 %>, and  <%= @movie.actor3 %></li>
				<li>Released <%= @movie.releaseyr %></li>
				<li>Genre: <%= @movie.genre %></li>
				<li><%= link_to "Buy Now!", @movie.purchase_link %></li>
			</ul>
			</div>
		</div>
		
		<div style="text-align:center">
		<%= content_tag(:iframe, nil, width:"560", height:"315", src: @movie.video_link)%>
		</div>
		
		<h2>Comments</h2>
		<% @movie.comments.each do |comment| %>
		  <p>
			<b>Commenter:</b>
			<%= comment.commenter %>
		  </p>
		 
		  <p>
			<b>Comment:</b>
			<%= comment.body %>
		  </p>
		  <p>
		  <% if !current_user.nil?%>
		  <% if current_user.admin||current_user.mod?%>
			<%= link_to 'Delete Comment', [@movie, comment],
					   :confirm => 'Are you sure?',
					   :method => :delete %>
		  <% end %>
 		  <% end %>
		</p>
		<% end %>

		<h2>Add a comment:</h2>
		<%= form_for([@movie, @movie.comments.build]) do |f| %>
		  <div class="field">
			<%= f.label :commenter %><br />
			<%= f.text_field :commenter %>
		  </div>
		  <div class="field">
			<%= f.label :body %><br />
			<%= f.text_area :body %>
		  </div>
		  <div class="actions">
			<%= f.submit %>
		  </div>
		<% end %>
		
		</br>
		<% if !current_user.nil?%>
		<% if current_user.admin?%>
			<div class="form-horizontal" >
				<%= button_to "Destroy", @movie, class:"btn btn-default", type:"button", method: :delete, data: { confirm: "You sure?" } %>
				<%= button_to 'Edit', edit_movie_path(@movie), type:"button", class:"btn btn-default" %>
			</div>
		<% end %>
		<% end %>
		</br>
		<%= link_to 'Back', index_path %>
	</div>
</div>
<%end%>